<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="USER-20170725RR" name="com.Case.Verilogin" tests="11" failures="1" timestamp="20 Sep 2017 03:30:29 GMT" time="167.584" errors="0">
  <testcase name="case33" time="13.854" classname="com.Case.Verilogin"/>
  <testcase name="case36" time="12.842" classname="com.Case.Verilogin"/>
  <testcase name="case38" time="17.792" classname="com.Case.Verilogin"/>
  <testcase name="case39" time="18.622" classname="com.Case.Verilogin"/>
  <testcase name="case40" time="11.126" classname="com.Case.Verilogin"/>
  <testcase name="case42" time="25.608" classname="com.Case.Verilogin">
    <failure type="java.lang.AssertionError" message="找不到控件:null expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 找不到控件:null expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.logic.login_Logic.oldlogin(login_Logic.java:105)
	at com.Case.Verilogin.case42(Verilogin.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- case42 -->
  <testcase name="case41" time="12.849" classname="com.Case.Verilogin"/>
  <testcase name="case37" time="12.780" classname="com.Case.Verilogin"/>
  <testcase name="case35" time="13.620" classname="com.Case.Verilogin"/>
  <testcase name="case34" time="13.747" classname="com.Case.Verilogin"/>
  <testcase name="case32" time="14.744" classname="com.Case.Verilogin"/>
</testsuite> <!-- com.Case.Verilogin -->
