<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test"
           tests="11"
           failures="1"
           errors="0"
           skipped="0"
           time="167.584">
  <properties />
            <testcase name="case42" time="25.608" classname="com.Case.Verilogin">
                <failure type="java.lang.AssertionError"
                  message="找不到控件:null expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: 找不到控件:null expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertTrue(Assert.java:42)
  com.logic.login_Logic.oldlogin(login_Logic.java:105)
  com.Case.Verilogin.case42(Verilogin.java:62)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="case41" time="12.849" classname="com.Case.Verilogin" />
                <testcase name="case39" time="18.622" classname="com.Case.Verilogin" />
                <testcase name="case35" time="13.620" classname="com.Case.Verilogin" />
                <testcase name="case34" time="13.747" classname="com.Case.Verilogin" />
                <testcase name="case33" time="13.854" classname="com.Case.Verilogin" />
                <testcase name="case36" time="12.842" classname="com.Case.Verilogin" />
                <testcase name="case38" time="17.792" classname="com.Case.Verilogin" />
                <testcase name="case37" time="12.780" classname="com.Case.Verilogin" />
                <testcase name="case32" time="14.744" classname="com.Case.Verilogin" />
                <testcase name="case40" time="11.126" classname="com.Case.Verilogin" />
      
</testsuite>
